steps:
  # Build the server Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/flock-manager-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/flock-manager-server:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-server'

  # Push the server image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/flock-manager-server:$COMMIT_SHA'
    id: 'push-server-sha'
    waitFor: ['build-server']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/flock-manager-server:latest'
    id: 'push-server-latest'
    waitFor: ['build-server']

  # Build the client Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/flock-manager-client:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/flock-manager-client:latest'
      - '-f'
      - 'client/Dockerfile'
      - 'client'
    id: 'build-client'

  # Push the client image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/flock-manager-client:$COMMIT_SHA'
    id: 'push-client-sha'
    waitFor: ['build-client']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/flock-manager-client:latest'
    id: 'push-client-latest'
    waitFor: ['build-client']

  # Deploy server to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flock-manager-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flock-manager-server:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy-server'
    waitFor: ['push-server-sha']

  # Deploy client to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flock-manager-client'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flock-manager-client:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy-client'
    waitFor: ['push-client-sha']

images:
  - 'gcr.io/$PROJECT_ID/flock-manager-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/flock-manager-server:latest'
  - 'gcr.io/$PROJECT_ID/flock-manager-client:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/flock-manager-client:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

